---
- name: Install neovim package.
  pacman:
    name:  neovim
    state: present

- include: config/main.yml

- include: config/golang.yml
  when:    golang

- include: config/platformio.yml
  when:    platformio

- include: config/rails.yml
  when:    rails

- name: Install vim-plug.
  get_url:
    url:  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: '{{ root }}/autoload/plug.vim'

- name:    Update plugins.
  command: nvim +PlugUpgrade +PlugInstall +PlugUpdate +qall
