---
- name: Install neovim package.
  pacman:
    name:  neovim
    state: present
  become: yes

- name: Create neovim config folders.
  file:
    path:  '{{ ansible_env.HOME }}/.config/nvim/{{ item }}'
    state: directory
  with_items:
    - autoload
    - bundle
    - config
    - env
    - ftplugin

- include: config/main.yml

- include: config/golang.yml
  when:    golang

- include: config/platformio.yml
  when:    platformio

- include: config/rails.yml
  when:    rails

- name: Install vim-plug.
  get_url:
    url:  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: '{{ ansible_env.HOME }}/.config/nvim/autoload/plug.vim'

- name: Install neovim pip package.
  pip:
    name: neovim
  become: yes

- name:    Update vim-plug.
  command: nvim +PlugUpgrade +qall!

- name:    Install plugins.
  command: "nvim '+silent! +PlugInstall!' +qall!"

- name:    Update plugins.
  command: "nvim '+silent! +PlugUpdate!' +qall!"
