---
- name: Install tmux package.
  pacman:
    name:  tmux
    state: present
  become: yes

- name: Install xsel package (required for tmux-yank plugin).
  pacman:
    name:  xsel
    state: present
  become: yes

- name: Install tpm.
  git:
    repo: https://github.com/tmux-plugins/tpm.git
    dest: '{{ ansible_env.HOME }}/.tmux/plugins/tpm'

- name: Install tmux config.
  template:
    src:  tmux.conf.j2
    dest: '{{ ansible_env.HOME }}/.tmux.conf'

- block:
    - name:    Install plugins.
      command: '{{ ansible_env.HOME }}/.tmux/plugins/tpm/bin/install_plugins'

    - name:    Update plugins.
      command: '{{ ansible_env.HOME }}/.tmux/plugins/tpm/bin/update_plugins all'

    - name:    Clean unused plugins.
      command: '{{ ansible_env.HOME }}/.tmux/plugins/tpm/bin/clean_plugins'

  environment:
    TMUX_PLUGIN_MANAGER_PATH: '{{ ansible_env.HOME }}/.tmux/plugins'
