---
- name: Install dependencies.
  pacman:
    name:  '{{ item }}'
    state: present
  with_items:
    - libvirt
    - qemu-headless
    - ebtables
    - dnsmasq
    - dmidecode
    - vinagre

- name: Enable libvirtd service.
  systemd:
    name:    libvirtd
    enabled: yes
